"""V2 Workflow 模块：编译器 + 子代理编排。

节点类型（与前端画布对齐）:
- ``start``     入口节点（接收用户消息）
- ``agent``     LLM 节点（system_prompt + model + tools 子集）
- ``tool``      工具节点（sandbox/skill/memory/task）
- ``subagent``  子代理节点（sequential 串行编排）
- ``end``       出口节点（返回最终回复）

连线 ``edge`` 表示数据流：``{source, target, source_handle?, target_handle?}``
编译器把 DAG 编译为 deepagents ``create_deep_agent`` 的 kwargs JSON。

子代理编排（V2-T4）:
- ``SubagentOrchestrator`` 按声明顺序串行执行 ``CompiledConfig.subagents``，
  每步输出作为下一步输入；与 deepagents 内置 ``task`` 工具（LLM 自主派发）
  互补，适合确定性流水线场景。
"""

from app.workflow.compiler import (
    NODE_TYPES,
    CompileError,
    CompiledConfig,
    compile_workflow,
    validate_definition,
)
from app.workflow.orchestrator import (
    OrchestratorError,
    OrchestratorResult,
    StepResult,
    SubagentOrchestrator,
    SubagentRunner,
    spec_from_compiled,
)
from app.workflow.model_router import (
    DEFAULT_TASK_STRATEGY,
    ModelRouter,
    ModelStrategy,
    default_router_from_env,
)
from app.workflow.evaluator import (
    BatchResult,
    CaseResult,
    EvalError,
    EvalRunner,
    assert_case,
    run_batch,
)
from app.workflow.observability import (
    Span,
    TraceCollector,
    traced_call,
)
from app.workflow.branch import (
    BranchRoute,
    NODE_TYPES_V25,
    eval_ex,
    extract_branches,
    select_route,
    validate_branch_nodes,
    EvalError as BranchEvalError,
)
from app.workflow.quota import (
    QuotaConfig,
    QuotaExceededError,
    QuotaManager,
    get_quota_manager,
    make_quota_dependency,
)
from app.workflow.hil import (
    ApprovalNodeSpec,
    DECISION_APPROVE,
    DECISION_CANCEL,
    DECISION_REJECT,
    HILError,
    INTERRUPT_APPROVED,
    INTERRUPT_CANCELLED,
    INTERRUPT_EXPIRED,
    INTERRUPT_PENDING,
    INTERRUPT_REJECTED,
    InterruptRequest,
    InterruptSink,
    build_resume_value,
    expire_overdue,
    get_interrupt_sink,
    list_my_approvals,
    request_approval,
    resume_interrupt,
    set_interrupt_sink,
    transition_status,
    validate_approval_nodes,
)
from app.workflow.rag import (
    LiveRAGService,
    RAGConfig,
    RAGContext,
    RAGCitation,
    RAGResult,
    RAGService,
    StubRAGService,
    get_rag_config,
    get_rag_service,
    query_knowledge,
    rag_config_from_env,
    reset_rag_service,
)
from app.workflow.audit import (
    AUDIT_DATA_ACCESS,
    AUDIT_OPERATION,
    AuditError,
    AuditEvent,
    AuditSink,
    RESULT_DENIED,
    RESULT_FAILURE,
    RESULT_SUCCESS,
    audit_log,
    get_audit_sink,
    purge_audit,
    query_audit,
    retention_days_from_env,
    set_audit_sink,
)
from app.workflow.parallel import (
    MERGE_ALL,
    MERGE_FIRST,
    MERGE_MERGE,
    ParallelError,
    ParallelOrchestrator,
    ParallelResult,
    ParallelStepResult,
    spec_from_compiled_parallel,
)
from app.workflow.mcp import (
    DEFAULT_CALL_TIMEOUT,
    DEFAULT_CONNECT_TIMEOUT,
    JSONRPC_VERSION,
    MCP_PROTOCOL_VERSION,
    TRANSPORT_HTTP,
    TRANSPORT_STDIO,
    TRANSPORTS,
    MCPClient,
    MCPConnectionError,
    MCPError,
    MCPProtocolError,
    MCPRegistry,
    MCPSecurityPolicy,
    MCPServerConfig,
    MCPTimeoutError,
    MCPToolDeniedError,
    MCPToolMeta,
    discover_mcp_tools,
    get_mcp_registry,
    mcp_servers_from_env,
    reset_mcp_registry,
)
from app.workflow.tool_market import (
    KNOWN_PERMISSIONS,
    HIGH_RISK_PERMISSIONS,
    PERM_DATABASE_READ,
    PERM_DATABASE_WRITE,
    PERM_ENV_READ,
    PERM_ENV_WRITE,
    PERM_FILESYSTEM_READ,
    PERM_FILESYSTEM_WRITE,
    PERM_MEMORY_READ,
    PERM_MEMORY_WRITE,
    PERM_NETWORK,
    PERM_SUBPROCESS,
    SOURCE_BUILTIN,
    SOURCE_MCP,
    SOURCE_SKILL,
    SOURCES,
    STATUS_DISABLED,
    STATUS_ENABLED,
    STATUS_INSTALLED,
    STATUS_UNINSTALLED,
    STATUSES,
    PluginConflictError,
    PluginError,
    PluginManifest,
    PluginManifestError,
    PluginNotFoundError,
    PluginPermissionError,
    PluginPermissionPolicy,
    PluginRecord,
    PluginRegistry,
    PluginSink,
    get_plugin_registry,
    install_manifest,
    reset_plugin_registry,
    set_plugin_registry,
    validate_manifest,
)
from app.workflow.release import (
    API_KEY_PREFIX,
    DEFAULT_STICKY_TTL,
    KEY_STATUSES,
    KEY_STATUS_ACTIVE,
    KEY_STATUS_EXPIRED,
    KEY_STATUS_REVOKED,
    KEY_STATUS_ROTATED,
    RELEASE_ACTIVE,
    RELEASE_ARCHIVED,
    RELEASE_DRAFT,
    RELEASE_PAUSED,
    RELEASE_STATUSES,
    WEIGHT_TOTAL,
    ApiKeyAlreadyRevokedError,
    ApiKeyError,
    ApiKeyNotFoundError,
    ReleaseError,
    ReleaseManager,
    ReleaseNotFoundError,
    ReleaseRecord,
    ReleaseSink,
    ReleaseValidationError,
    generate_api_key,
    get_release_manager,
    hash_api_key,
    is_expired,
    key_prefix,
    reset_release_manager,
    select_version,
    set_release_manager,
    validate_weights,
)
from app.workflow.otel import (
    DEFAULT_SERVICE_NAME,
    MetricsRegistry,
    OTelConfig,
    get_metrics_registry,
    get_otel,
    metrics_middleware,
    render_metrics,
    reset_metrics_registry,
    reset_otel,
    setup_otel,
    trace_collector_hook,
)
from app.workflow.adversarial import (
    ADVERSARIAL_STRATEGIES,
    MERGE_JUDGE,
    MERGE_VOTE,
    AdversarialOrchestrator,
    AdversarialResult,
    default_vote_fn,
)

__all__ = [
    # 编译器
    "NODE_TYPES",
    "CompileError",
    "CompiledConfig",
    "compile_workflow",
    "validate_definition",
    # 子代理编排
    "OrchestratorError",
    "OrchestratorResult",
    "StepResult",
    "SubagentOrchestrator",
    "SubagentRunner",
    "spec_from_compiled",
    # 模型路由
    "DEFAULT_TASK_STRATEGY",
    "ModelRouter",
    "ModelStrategy",
    "default_router_from_env",
    # 评测
    "BatchResult",
    "CaseResult",
    "EvalError",
    "EvalRunner",
    "assert_case",
    "run_batch",
    # 可观测性
    "Span",
    "TraceCollector",
    "traced_call",
    # V2.5-T1 条件分支
    "BranchRoute",
    "NODE_TYPES_V25",
    "eval_ex",
    "extract_branches",
    "select_route",
    "validate_branch_nodes",
    "BranchEvalError",
    # V2.5-T8 配额限流
    "QuotaConfig",
    "QuotaExceededError",
    "QuotaManager",
    "get_quota_manager",
    "make_quota_dependency",
    # V2.5-T2 人机协同
    "ApprovalNodeSpec",
    "DECISION_APPROVE",
    "DECISION_CANCEL",
    "DECISION_REJECT",
    "HILError",
    "INTERRUPT_APPROVED",
    "INTERRUPT_CANCELLED",
    "INTERRUPT_EXPIRED",
    "INTERRUPT_PENDING",
    "INTERRUPT_REJECTED",
    "InterruptRequest",
    "InterruptSink",
    "build_resume_value",
    "expire_overdue",
    "get_interrupt_sink",
    "list_my_approvals",
    "request_approval",
    "resume_interrupt",
    "set_interrupt_sink",
    "transition_status",
    "validate_approval_nodes",
    # V2.5-T4 RAG 接口预留
    "LiveRAGService",
    "RAGConfig",
    "RAGContext",
    "RAGCitation",
    "RAGResult",
    "RAGService",
    "StubRAGService",
    "get_rag_config",
    "get_rag_service",
    "query_knowledge",
    "rag_config_from_env",
    "reset_rag_service",
    # V2.5-T9 审计日志
    "AUDIT_DATA_ACCESS",
    "AUDIT_OPERATION",
    "AuditError",
    "AuditEvent",
    "AuditSink",
    "RESULT_DENIED",
    "RESULT_FAILURE",
    "RESULT_SUCCESS",
    "audit_log",
    "get_audit_sink",
    "purge_audit",
    "query_audit",
    "retention_days_from_env",
    "set_audit_sink",
    # V2.5-T3 并行子代理
    "MERGE_ALL",
    "MERGE_FIRST",
    "MERGE_MERGE",
    "ParallelError",
    "ParallelOrchestrator",
    "ParallelResult",
    "ParallelStepResult",
    "spec_from_compiled_parallel",
    # V2.5-T6 MCP 协议支持
    "DEFAULT_CALL_TIMEOUT",
    "DEFAULT_CONNECT_TIMEOUT",
    "JSONRPC_VERSION",
    "MCP_PROTOCOL_VERSION",
    "TRANSPORT_HTTP",
    "TRANSPORT_STDIO",
    "TRANSPORTS",
    "MCPClient",
    "MCPConnectionError",
    "MCPError",
    "MCPProtocolError",
    "MCPRegistry",
    "MCPSecurityPolicy",
    "MCPServerConfig",
    "MCPTimeoutError",
    "MCPToolDeniedError",
    "MCPToolMeta",
    "discover_mcp_tools",
    "get_mcp_registry",
    "mcp_servers_from_env",
    "reset_mcp_registry",
    # V2.5-T7 工具市场骨架
    "KNOWN_PERMISSIONS",
    "HIGH_RISK_PERMISSIONS",
    "PERM_DATABASE_READ",
    "PERM_DATABASE_WRITE",
    "PERM_ENV_READ",
    "PERM_ENV_WRITE",
    "PERM_FILESYSTEM_READ",
    "PERM_FILESYSTEM_WRITE",
    "PERM_MEMORY_READ",
    "PERM_MEMORY_WRITE",
    "PERM_NETWORK",
    "PERM_SUBPROCESS",
    "SOURCE_BUILTIN",
    "SOURCE_MCP",
    "SOURCE_SKILL",
    "SOURCES",
    "STATUS_DISABLED",
    "STATUS_ENABLED",
    "STATUS_INSTALLED",
    "STATUS_UNINSTALLED",
    "STATUSES",
    "PluginConflictError",
    "PluginError",
    "PluginManifest",
    "PluginManifestError",
    "PluginNotFoundError",
    "PluginPermissionError",
    "PluginPermissionPolicy",
    "PluginRecord",
    "PluginRegistry",
    "PluginSink",
    "get_plugin_registry",
    "install_manifest",
    "reset_plugin_registry",
    "set_plugin_registry",
    "validate_manifest",
    # V2.5-T10 API Key 轮转 + 灰度发布
    "API_KEY_PREFIX",
    "DEFAULT_STICKY_TTL",
    "KEY_STATUSES",
    "KEY_STATUS_ACTIVE",
    "KEY_STATUS_EXPIRED",
    "KEY_STATUS_REVOKED",
    "KEY_STATUS_ROTATED",
    "RELEASE_ACTIVE",
    "RELEASE_ARCHIVED",
    "RELEASE_DRAFT",
    "RELEASE_PAUSED",
    "RELEASE_STATUSES",
    "WEIGHT_TOTAL",
    "ApiKeyAlreadyRevokedError",
    "ApiKeyError",
    "ApiKeyNotFoundError",
    "ReleaseError",
    "ReleaseManager",
    "ReleaseNotFoundError",
    "ReleaseRecord",
    "ReleaseSink",
    "ReleaseValidationError",
    "generate_api_key",
    "get_release_manager",
    "hash_api_key",
    "is_expired",
    "key_prefix",
    "reset_release_manager",
    "select_version",
    "set_release_manager",
    "validate_weights",
    # V2.5-T12 OTel 全链路可观测 + 告警
    "DEFAULT_SERVICE_NAME",
    "MetricsRegistry",
    "OTelConfig",
    "get_metrics_registry",
    "get_otel",
    "metrics_middleware",
    "render_metrics",
    "reset_metrics_registry",
    "reset_otel",
    "setup_otel",
    "trace_collector_hook",
    # V3-T7 adversarial 子代理
    "ADVERSARIAL_STRATEGIES",
    "MERGE_JUDGE",
    "MERGE_VOTE",
    "AdversarialOrchestrator",
    "AdversarialResult",
    "default_vote_fn",
]
