apiVersion: v1
kind: Service
metadata:
  name: {{ include "super-agent.backendFullname" . }}
  labels:
    {{- include "super-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - name: http
      port: {{ .Values.service.backend.port }}
      targetPort: http
  selector:
    {{- include "super-agent.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
